version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '15.11.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check node version
          command: node --version
      - run:
          name: Check npm version
          command: npm --version
      - run: npm run test
workflows:
  test_my_app:
    jobs:
      - test