version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '15.11.0'
    steps:
      - checkout
      - run:
          name: Check node version
          command: node --version
      - node/install-npm:
          version: '7.8.0'
      - run:
          name: Check npm version
          command: npm --version
      - node/install-packages
      - run:
          name: Build code
          command: npm run build -- --verbose
      - run: npm run test -- --verbose
workflows:
  test_my_app:
    jobs:
      - test