version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '15.14.0'
    steps:
      - checkout
      - run:
          name: Check node version
          command: node --version
      - node/install-npm:
          version: '7.13.0'
      - run:
          name: Check npm version
          command: npm --version
      - node/install-packages
      - run:
          name: Build code
          command: npm run build -- --verbose
      - run:
          name: Run tests
          command: npm run test -- --verbose --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

workflows:
  test_my_app:
    jobs:
      - test